### ISSUE TITLE
Что нужно доделать

### ISSUE THREAD

**Issue by Obukhov-Artem** [makcimbx/TSTU-Laba-2#1]
После авторизация - на главной странице никак не отображается юзернейм. И при добавлении сообщения авторизация не учитывается. Есть проблемы в коде - некоторые списки у тебя явно глобальные, но в функциях ты это не указываешь.  Непонятно, добавляются новые юзеры в словарь и вообще работает ли проверка на логин-пароль (ощущение, что данные с формы в цикле посмотрели, но никакого результата с этого не получили). Пока работа выполнена на 2/3, нужно эти моменты поправить.

**Comment by makcimbx** [comment]
Никнейм отображался, там сверху Hi, Неизвестный если не залогинен было, и с ником если залогинен, сейчас переделал, пока не залогинишься вообще ничего не сделаешь. Вообщем доделал логин пароль. Спасибо @didim99 помог с этим, а то я бы свихнулся от этого питона и его рекурсий импорта.
